name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
source:         source
destination:    content
encoding:       UTF-8
highlighter:    rouge
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Simplifies introducing changes related to the latest release
current_version: 2.5.10.1
current_version_short: 25101
archetype_version: 2.5.5
current_beta_version: 2.5-BETA3
current_beta_version_short: 25B3
release_date: 7 March 2017
release_date_short: 20170307
beta_release_date_short: 20160126

# Allows to directly edit pages on GitHub
repository_url: https://github.com/apache/struts-site
