name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
source:         source
destination:    target/content
encoding:       UTF-8
highlighter:    rouge
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Simplifies introducing changes related to the latest release
current_version: 2.5.16
current_version_short: 2516
archetype_version: 2.5.14
current_beta_version: 2.5-BETA3
current_beta_version_short: 25B3
release_date: 16 March 2018
release_date_short: 20180316
beta_release_date_short: 20160126

# Allows directly edit pages on GitHub
repository_url: https://github.com/apache/struts-site

# Used to generate links to Struts Core ApiDocs
apidocs: /maven/struts2-core/apidocs

# Confluence main site
wiki_url: https://cwiki.apache.org/confluence/display/WW
