name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
source:         source
destination:    content
encoding:       UTF-8
kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    wrap:              div
    line_numbers:      inline
    line_number_start: 1
    tab_width:         4
    bold_every:        10
    css:               style

# Defines root of the site:
# "" - when you want to deploy to production
# "." - if you want to test the site at your home folder at Apache (ie. http://people.apache.org/~lukaszlenart)
root:

# Simplifies introducing changes related to the latest release
current_version: 2.3.28
current_version_short: 2328
current_beta_version: 2.5-BETA3
current_beta_version_short: 25
release_date: 18 march 2016
release_date_short: 20160318
beta_release_date_short: 20160126
