name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
highlighter:    pygments
source:         source
destination:    content
encoding:       UTF-8
kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Defines root of the site:
# "" - when you want to deploy to production
# "." - if you want to test the site at your home folder at Apache (ie. http://people.apache.org/~lukaszlenart)
root:

# Simplifies introducing changes related to the latest release
current_version: 2.3.24.1
current_version_short: 2324.1
current_beta_version: 2.5-BETA1
current_beta_version_short: 25
release_date: 24 september 2015
release_date_short: 20150924
beta_release_date_short: 20150731
