name: Apache Struts
markdown: redcarpet
markdown_ext: md
pygments: true
source: source
destination: content
encoding: UTF-8

# Defines root of the site:
# "" - when you want to deploy to production
# "." - if you want to test the site at your home folder at Apache (ie. http://people.apache.org/~lukaszlenart)
root:
