name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
source:         source
destination:    content
encoding:       UTF-8
kramdown:
  auto_id_stripping:  true
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    wrap:              div
    tab_width:         4
    bold_every:        10
    css:               style

# Simplifies introducing changes related to the latest release
current_version: 2.5.10.1
current_version_short: 25101
archetype_version: 2.5.5
current_beta_version: 2.5-BETA3
current_beta_version_short: 25B3
release_date: 7 March 2017
release_date_short: 20170307
beta_release_date_short: 20160126
